# Generated by Django 5.0.4 on 2024-05-09 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=120)),
                ('folder_status', models.CharField(choices=[('PRIVATE', 'Shaxsiy'), ('PUBLIC', 'Hamma uchun')], default='PRIVATE', max_length=15)),
                ('folder_photo', models.ImageField(blank=True, null=True, upload_to='arxiv/folders/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_status', models.CharField(choices=[('PRIVATE', 'Shaxsiy'), ('PUBLIC', 'Hamma uchun')], default='PRIVATE', max_length=20)),
                ('file_name', models.CharField(max_length=120)),
                ('about_file', models.TextField(blank=True, null=True)),
                ('file_type', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='arxiv/files/<django.db.models.fields.CharField>/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxiv.folders')),
            ],
        ),
    ]
