# Generated by Django 5.0.4 on 2024-05-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arxiv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folders',
            name='folder_status',
        ),
    ]
