# Generated by Django 5.0.4 on 2024-05-09 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxiv', '0002_remove_folders_folder_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'file', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='folders',
            options={'verbose_name': 'Folder', 'verbose_name_plural': 'Folders'},
        ),
        migrations.AlterField(
            model_name='files',
            name='file_folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='arxiv.folders'),
        ),
    ]
